database/user.go
When restarting the bridge, the management room got overwritten by an empty value.
The reason is, that it was not read out of the database.
=> parse management room from database as well

user.go
After user succesfully sets up bridge, bot will tell what to do next. This info had still old command so I updated message to reflect new 'sync' directive.
=> Change help message to 'sync' instead 'import contacts'

database/database.go, database/message.go, database/portal.go, database/puppet.go, database/user.go, example-config.yaml, go.mod, main.go
Implemented postgresql connection for better stability.
=> Implemented postgres

commands.go
This fixes panics that happen because the handlers assume the user is logged
in when the command is executed.
I'm not sure on the code style. A switch inside a switch is a bit ugly, and error prone. I would be happy to change it if desired!
Example of a panic that happened:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x928d7c]
goroutine 127 [running]:
main.(*CommandHandler).CommandList(0xc0001783c0, 0xc00016bef8)
/build/commands.go:186 +0x6c
main.(*CommandHandler).Handle(0xc0001783c0, 0xc000455920, 0x1b,
0xc0002480c0, 0xc000250470, 0x4)
/build/commands.go:89 +0x1f3
main.(*MatrixHandler).HandleMessage(0xc000176db0, 0xc0001ae6c0)
/build/matrix.go:161 +0x203
created by …
=> Disallow using session commands when not logged in

config/bridge.go, example-config.yaml, portal.go
This patch allow matrix user (which use whatsapp-bridge) invite to room any other bots, which can help matrix user. 
For example - bot, which translate voice messages to text:
https://github.com/progserega/voice2textMatrix
=> set default permission to invite bots to matrix room of whatsapp-bridge

user.go
When WhatsApp disconnected, this error would appear in a 1-1 room. Since the command prefix is never used in this room it's a little confusing.
This PR removes the command prefix from the error message.
=> Remove command prefix from reconnect prompt

go.mod, go.sum, portal.go
We need to convert them to png, otherwise synapse has trouble
thumbnailing them. Also the default webp decoder can't decode WhatsApp
stickers, so we use the chai2010 decoder.
This currently only implements receiving stickers as go-whatapp doesn't support sending stickers yet? I don't know if adding a bool to HandleMediaMessage is the right way to go, but I don't know how to do it better.
=> Receive stickers from whatsapp

database/upgrades/2019-11-12-fix-room-topic-length.go, database/upgrades/upgrades.go
Room topics in WhatsApp do have a maximum length of 512.
Currently, the column topic is described as VARCHAR(255), which leads to the following error:
Whenever you accept an invitation from a WhatsApp groups with a topic above 255 characters, you get added and everything seems to work well. However, PostgreSQL throws the following error:
```
STATEMENT:  UPDATE portal SET mxid=$1, name=$2, topic=$3, avatar=$4, avatar_url=$5 WHERE jid=$6 AND receiver=$7,
ERROR:  value too long for type character varying(255)
```
Next time you restart the bridge, it has forgotten the reference in portal, so you get invited again and can't use the old room. 
This fix is PSQL only, because, as you already mentioned in https://github.com/tulir/mautrix-whatsapp/blob/3caca1b9a0eeb4521605d59416ede2ec8eec8cb0/databa …
=> Fix room topic length

portal.go
This allows people to build the bridge with Go 1.11, the current version in Debian stable.
=> Replace ReplaceAll(…) with Replace(…, -1)

portal.go
A while back you implemented a fix because WhatsApp was sending incorrect mime type (3:<). However after some testing I found that WhatsApp now sends correct mimetypes, and the fix you implemented caused .ogg voice messages to instead be seen as .ogx (as described in #134). Removing this workaround seems to not break anything, and voice messages now correctly get bridged as .oga files (which are just an updated version of .ogg). 
Though, since you are the person who ran into this problem in the first place, it might be an idea to check whether WhatsApp truly sends all mimetypes correctly.
Fixes #134
=> Fix #134, let whatsapp deal with mimetypes

example-config.yaml
I was struggling trying to get the bridge to make a community for me. Turns out Synapse doesn't allow it by default.
Even though the bridge's logs give insight in the issue, it would be great to have the config explain it as well.
I also thought about mentioning the specific Synapse config value, but it wouldn't be clean to have things specific to a single homeserver implementation here.
Thus change hardly deserves its own pull request, but oh well.
=> Improve communities doc in config

commands.go
Prevent command `list` from failing with out of range access error if number
of entries is lower than maximum entry index for that page a.k.a.
if `len(result) < page*max`
=> Fix out of range access when requesting last page with `list`

portal.go, whatsapp-ext/whatsapp.go
Fixes #228
Bridge didn't set the power level for message sending correctly when the bridge user is invited to a WA-group that was already set to 'announce'-mode (=only admins can send message).
It did already bridge it correctly when the setting is toggled while we're in the group. (Using ChatUpdate with ChatActionType Announce)
In this patch I've added a call to RestrictMessageSending in CreateMatrixRoom which should fix it for new groups bridge users join. I could have also added a state event in the initialState slice, instead of calling RestrictMessageSending separately, but that would make it more complex imo. Let you know if you'd want me to change it.
The extra call to RestrictMessageSending in UpdateMetadata is included to fix it for existing groups as well. Works perfectly here! …
=> Set RestrictMessageSending in portal create+update

commands.go
Remove the apostrophe that only the help text of "login-matrix" is ending with.
=> Help text of login-matrix: Remove trailing apostrophe

database/migrate.go
This fixes the dbms migration by using the latest set of columns.
FYI, that's the latest version of the SQL scheme:
<details>
```
CREATE TABLE portal (
jid VARCHAR(255), 
receiver VARCHAR(255), 
mxid VARCHAR(255) UNIQUE, 
name VARCHAR(255) NOT NULL, 
topic VARCHAR(255) NOT NULL, 
avatar VARCHAR(255) NOT NULL, 
avatar_url VARCHAR(255), 
encrypted BOOLEAN NOT NULL DEFAULT false, 
first_event_id TEXT NOT NULL DEFAULT '', 
next_batch_id TEXT NOT NULL DEFAULT '', 
relay_user_id TEXT, 
PRIMARY KEY (jid, receiver)
);
CREATE TABLE puppet (
username VARCHAR(255) PRIMARY KEY, 
avatar VARCHAR(255), 
displayname VARCHAR(255), 
name_quality SMALLINT, 
custom_mxid VARCHAR(255), 
access_token VARCHAR(1023), 
next_batch VARCHAR(255), 
avatar_url VARCHAR(255), 
enable_presence BOOLEAN NOT NULL DEFAULT …
```
=> Fix DBMS migration

commands.go
Update sync command help response string to include newly added functionality - space
=> fix Sync cmd help: Add space argument

config/bridge.go, config/upgrade.go, example-config.yaml, portal.go
This is a workaround to be able to get presence working for homeservers that do not support it.
Since online presence is required to receive typing notifications from users on WA, this allows the users of the bridge to at least see if the contact is typing during a conversation. Otherwise, there is no feedback.
=> Send presence when typing changes

historysync.go
* INITIAL_BOOTSTRAP doesn't have 100% as the progress
* Enqueue deferred backfills after both RECENT and FULL progress gets to
the necessary levels
=> historysync: fix backfill logic again

database/backfillqueue.go, database/historysync.go, portal.go
This can happen if the user gets kicked from a chat.
=> backfill: skip chats if the user is not a participant

config/bridge.go, database/historysync.go, example-config.yaml, historysync.go, user.go
Adds an option to mark unread during backfill using the MSC2867 room account data.
=> backfill: add option to mark unread using account data

go.mod, go.sum, portal.go, user.go
When user leaves a WA group chat, and no other Matrix users are using its portal, delete the portal.
When user deletes a chat ("delete" button in whatsapp that's visible on left groups and 1:1 chats), and no other Matrix users are using its portal, delete the portal.
=> Handle delete chat and leave WA group chat

config/bridge.go, config/upgrade.go, example-config.yaml, historysync.go
Signed-off-by: Sumner Evans <sumner@beeper.com>
=> backfill: add option to only sync unread state if chat is younger than threshold

bridgestate.go, provisioning.go
Change bridge state remote ID to remain constant across a reconnect, and change return status of logout to 200 when already logged out
=> Fix reconnect on remote logout issues

metrics.go, user.go
Fixes #619 
Decided in the end not to use a status code, but just a reason string.
=> Add a metric for connection failures

historysync.go
Defer initializing portal on backfill until there are messages.
=> Prevent creating portals for non-backfillable conversations

pkg/connector/config.go
This makes it possible to create and modify the config instance in another project.
=> Add `config.PostProcess` method
