Dockerfile, docker-run.sh
Set it using the env variable UID and GUID, as it is done in tulir/mautrix-telegram
=> Allow to set uid guid when running whatsapp program

main.go
=> Add comma to sentence

database/upgrades/2019-08-25-move-state-store-to-db.go
This solved #101 for me. I'm not very familiar with go if there is a better way to implement this let me know.
And thank you for all the hard work on this project
=> Migrate registrations in batches

custompuppet.go, go.mod, go.sum
I've been playing with tulir/mautrix-whatsapp#119 and since you mentioned it would need a mautrix-go update, I tried to do that.
=> updated to latest mautrix-go and mautrix-appservice-go

portal.go
Should let bots be bridged. Not tested yet.
=> portal: bridge notices

portal.go
Tested it a bit, and it seems to work.
Fixes #199
=> Use WhatsApp document filename for document type files

database/database.go, main.go
=> Make database log a sublogger of Bridge, like all other modules.

matrix.go, portal.go
Depends on https://github.com/mautrix/go/pull/49
=> checkpoints: send retry_num

go.mod, go.sum, portal.go
Uses `HEAD` of https://github.com/mautrix/go/pull/58
=> voice messages: bridge from WhatsApp to native Matrix voice messages

portal.go, urlpreview.go
Uses com.beeper.linkpreviews instead of com.beeper.linkpreview
=> link previews: update to support a list

config/config.go, config/upgrade.go, example-config.yaml, provisioning.go, segment.go
=> segment: add for provisioning API

backfillqueue.go, historysync.go
This makes it so that the timestamp of the chat in Matrix looks correct,
even though the message is not there to be bridged since it has
disappeared.
=> backfill: add notification of disappearing messages at correct timestamp

provisioning.go
```
$ curl 'http://localhost:29318/_matrix/provision/v1/contacts?user_id=@sumner:localhost' -H 'Authorization: Bearer XXXXXXXXXXX' | jq
{
"1231231234@s.whatsapp.net": {
"AvatarURL": "mxc://localhost/kieLZORdCRhjidCSuQjfDVGs",
"BusinessName": "",
"FirstName": "",
"Found": true,
"FullName": "Foo",
"PushName": ""
},
"3453453457@s.whatsapp.net": {
"AvatarURL": "mxc://localhost/XxgPEAYxGJUwtsDwdojXekDq",
"BusinessName": "",
"FirstName": "Bar",
"Found": true,
"FullName": "",
"PushName": ""
}
}
```
=> provisioning/contacts: send avatar URL

provisioning.go
Signed-off-by: Sumner Evans <sumner@beeper.com>
=> provisioning/list_contacts: make augmentation with avatar more efficient

database/portal.go
The % needs to be escaped in the LIKE statement.
Closes #532
=> Fix the FindPrivateChats SELECT statement

historysync.go, portal.go
Signed-off-by: Sumner Evans <sumner@beeper.com>
=> historysync: fix typo

go.mod, go.sum
=> Add Matrix media fetch retries

pkg/connector/startchat.go
Signed-off-by: Sumner Evans <sumner.evans@automattic.com>
=> connector/startchat: check for logged in before listing contacts

go.mod, go.sum, pkg/connector/chatinfo.go, pkg/connector/events.go, pkg/waid/dbmeta.go
Depends on https://github.com/mautrix/go/pull/386
=> handlewhatsapp: sync member list on first lid message

pkg/msgconv/from-whatsapp.go, pkg/msgconv/wa-misc.go
one step closer to no more "unknown message type"
=> msgconv/from-whatsapp: add better placeholder for pinning messages

pkg/msgconv/from-whatsapp.go, pkg/msgconv/wa-misc.go
https://github.com/user-attachments/assets/2e1bb0c0-c8c0-4683-bd46-48ab71c4e761
```
richResponseMessage {
messageType: AI_RICH_RESPONSE_TYPE_STANDARD
submessages {
messageType: AI_RICH_RESPONSE_TEXT
messageText: "Hey! What\'s up?"
}
unifiedResponse {
data: "{\"response_id\":\"f3b6b2e1-9d41-4e9d-b2a0-0b7fcd8a2c58\",\"sections\":[{\"view_model\":{\"primitive\":{\"text\":\"Hey! What\'s up?\",\"__typename\":\"GenAIMarkdownTextUXPrimitive\"},\"__typename\":\"GenAISingleLayoutViewModel\"}}]}"
}
}
messageContextInfo {
botMetadata {
botResponseID: "f3b6b2e1-9d41-4e9d-b2a0-0b7fcd8a2c58"
}
}
richResponseMessage {
messageType: AI_RICH_RESPONSE_TYPE_STANDARD
submessages {
messageType: AI_RICH_RESPONSE_TEXT
messageText: "Hey"
}
unifiedResponse {
data: …
```
=> msgconv/from-whatsapp: add better support for meta ai responses
